### PR TITLE
Support ipv6

### PR DESCRIPTION
**Pull request by M0r13n**
This PR adds some useful metrics around IPv6. Namely:

- IPv6 reachable addresses
- IPv6 Firewall rules

### CODE REVIEW

**Comment by akpw** [comment]
hey @M0r13n, a quick comment: considering `ipv6_neighbor = False` in the config file, probably makes sense to put `FE_IPV6_NEIGHBOR_KEY` into `BOOLEAN_KEYS_NO`, i.e. disabled by default?

**Comment by akpw** [comment]
merged & addressed the above comment

**Comment by akpw** [comment]
@M0r13n I also made ipv6 firewall metrics optional & disabled by default, since not all routeros6.x devices have the ipv6 package installed

**Comment by M0r13n** [comment]
@akpw Good points. Thanks for improving my PR!

**Comment by akpw** [comment]
@M0r13n sure, thanks for submitting this PR in the first place. ipv6 support was a long standing feature request, mentioned in e.g. #9  

Regarding `BOOLEAN_KEYS_xx`, one general consideration there is compatibility with existing mktxp installations. When adding a feature that could have an impact, `BOOLEAN_KEYS_NO` ensures the feature is added into production `mktxp.conf` as False -- thus not interfering with anything and also making it easier for the users to turn it on as needed.

`BOOLEAN_KEYS_YES` has an opposite effect, and so even if you put False in the initial bundled conf it's not going to replace the already existing production configurations. Now because of the `BOOLEAN_KEYS_YES` membership,  the feature will be set in the production `mktxp.conf`s as `True` thus potentially interfering with non-supported devices etc.

**Comment by M0r13n** [comment]
@akpw thats a good point. I‘ll keep that in mind for the next PR

**Pull request merged**
