### PR TITLE
Add Parsing of the routeros version for capsman metrics

### PR DESCRIPTION
**Pull request by mjkantti**
As stated in the issue: https://github.com/akpw/mktxp/issues/106
New versions of RouterOS (>7.13) have the wifi capsman ability builtin.

Added functionality to check if the routeros version is post 7.13, and use wifi wireless version if so.

### CODE REVIEW

**Comment by akpw** [comment]
@mjkantti thanks for the PR. A few comments:
 - there is already a [function to determine the firmware version](https://github.com/akpw/mktxp/blob/7cb89a65d654c1610e366ee1badba3db2fcbff2e/mktxp/datasource/routerboard_ds.py), probably makes sense just use it instead of implementing a new one
 - the naming, `is_os_with_wifi_builtin` might also be a bit confusing since the check is for location of capsman capabilities that got moved as of 7.13

can you pls check on those?

**Comment by mjkantti** [comment]
Thanks for the review @akpw 

I thought about using the firmware_version but as it is different than routeros version, I'm not sure if using that would be a good idea.. (It is possible to run older firmware on newer routeros). Do you think that using the firmware version as opposed to routeros version is adequate?

As for the naming, I will fix that.

**Comment by mjkantti** [comment]
@akpw I renamed functions and created a new function called os_version. What do you think about this?

**Comment by akpw** [comment]
looks OK to me

**Pull request merged**
